RestaurantManagementSystem/Controllers/BillController.cs
using RestaurantManagementSystem.CustomExceptions;
using RestaurantManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace RestaurantManagementSystem.Controllers
{
    public class BillController : Controller
    {
        ManagerModel managerModel = new ManagerModel();
        // GET: Bill
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult AddBill()
        {
            ViewBag.Data = managerModel.GetStaffDetails();
            return View();
        }
        [HttpPost]
        public ActionResult AddBill(BillModel billModel, StaffModel staffModel)
        {
            try
            {
                billModel.BillDate = DateTime.Now;
                int rowsAffected = managerModel.AddBill(billModel, staffModel);
                ViewBag.Data = managerModel.GetStaffDetails();
                if (ViewBag.Data != null && rowsAffected > 0)
                {
                    ViewBag.Message = "Bill generated Succesfully";
                }
                else
                {
                    ViewBag.Message = "Unable to generate bill";
                }
            }
            catch (CustomSqlException ex)
            {
                ViewBag.Message = ex.Message;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View();
        }
        [HttpGet]
        public ActionResult GetBillDetails()
        {
            try
            {
                var billModels = managerModel.GetBillDetails();
                return View(billModels);
            }
            catch (NoDataFoundException ex)
            {
                ViewBag.Message = ex.Message;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View("Index","Home");
        }
        [HttpGet]
        public ActionResult GetBillsByDate()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetBillsByDate(string billDate)
        {
            string[] dates = billDate.Split('-');
            int year = int.Parse(dates[0]);
            int month = int.Parse(dates[1]);
            int day = int.Parse(dates[2]);

            List<BillModel> bills = managerModel.GetBillsByDate(year,month,day);
            ViewBag.Total ="Total Amount :"+managerModel.CalculateTotal(bills);
            ViewBag.Bills = bills;

            return View();
        }
    }
}

RestaurantManagementSystem/Controllers/StaffController.cs
using RestaurantManagementSystem.CustomExceptions;
using RestaurantManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurantManagementSystem.Controllers
{
    public class StaffController : Controller
    {
        readonly ManagerModel managerModel = new ManagerModel();
        // GET: Staff
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult AddStaff()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddStaff(StaffModel staffModel)
        {
            try
            {
                int rowsAffected = managerModel.AddStaff(staffModel);
                if (rowsAffected > 0)
                {
                    ViewBag.Message = "Staff added succesfully";
                }
                else
                {
                    ViewBag.Message = "Unable to add staff";
                }
            }
            catch (CustomSqlException ex)
            {
                ViewBag.Message = ex.Message;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View();
        }
        [HttpGet]
        public ActionResult GetStaffDetails()
        {
            try
            {
                List<StaffModel> staffs = new List<StaffModel>();
                staffs = managerModel.GetStaffDetails();
                return View(staffs);
            }
            catch (NoDataFoundException ex)
            {
                ViewBag.Message = ex.Message;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View("Index", "Home");
        }
    }
}

RestaurantManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Restaurant Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Add Staff", "AddStaff", "Staff")</li>
                        <li>@Html.ActionLink("Staff Details", "GetStaffDetails", "Staff")</li>
                        <li>@Html.ActionLink("Add Bill", "AddBill", "Bill")</li>
                        <li>@Html.ActionLink("Get Bills", "GetBillDetails", "Bill")</li>
                        <li>@Html.ActionLink("Get Bills by Date", "GetBillsByDate", "Bill")</li>
                    </ul>
                </div>
            </div>
        </div>
            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                </footer>
            </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
       
    </body>
</html>